/**
 * Permission codes follow `<module>:<action>`. Seeded into the permissions
 * table and attached to roles; guards compare against the caller's effective set.
 */
export const PERMISSIONS = {
  USER_READ: 'user:read',
  USER_WRITE: 'user:write',
  ROLE_READ: 'role:read',
  ROLE_WRITE: 'role:write',
  DEPARTMENT_READ: 'department:read',
  DEPARTMENT_WRITE: 'department:write',
  PROJECT_READ: 'project:read',
  PROJECT_WRITE: 'project:write',
  CATEGORY_READ: 'category:read',
  CATEGORY_WRITE: 'category:write',
  PR_READ: 'purchase_request:read',
  PR_READ_ALL: 'purchase_request:read_all',
  PR_WRITE: 'purchase_request:write',
  PR_REVIEW: 'purchase_request:review',
  SUPPLIER_READ: 'supplier:read',
  SUPPLIER_WRITE: 'supplier:write',
  SUPPLIER_APPROVE: 'supplier:approve',
  RFQ_READ: 'rfq:read',
  RFQ_WRITE: 'rfq:write',
  RFQ_AWARD: 'rfq:award',
  QUOTATION_READ: 'quotation:read',
  QUOTATION_WRITE: 'quotation:write',
  PO_READ: 'purchase_order:read',
  PO_WRITE: 'purchase_order:write',
  PO_ISSUE: 'purchase_order:issue',
  PO_ACKNOWLEDGE: 'purchase_order:acknowledge',
  CONTRACT_READ: 'contract:read',
  CONTRACT_WRITE: 'contract:write',
  CERTIFICATE_READ: 'certificate:read',
  CERTIFICATE_WRITE: 'certificate:write',
  DASHBOARD_READ: 'dashboard:read',
  REPORT_READ: 'report:read',
  AUDIT_READ: 'audit:read',
  AI_USE: 'ai:use',
  SETTING_WRITE: 'setting:write',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER',
  BUYER: 'BUYER',
  DEPARTMENT_MANAGER: 'DEPARTMENT_MANAGER',
  END_USER: 'END_USER',
  SUPPLIER: 'SUPPLIER',
  FINANCE: 'FINANCE',
  QA: 'QA',
  WAREHOUSE: 'WAREHOUSE',
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];

const ALL = Object.values(PERMISSIONS);

const BUYER_PERMISSIONS: PermissionCode[] = [
  PERMISSIONS.USER_READ,
  PERMISSIONS.DEPARTMENT_READ,
  PERMISSIONS.PROJECT_READ,
  PERMISSIONS.CATEGORY_READ,
  PERMISSIONS.CATEGORY_WRITE,
  PERMISSIONS.PR_READ,
  PERMISSIONS.PR_READ_ALL,
  PERMISSIONS.PR_REVIEW,
  PERMISSIONS.SUPPLIER_READ,
  PERMISSIONS.SUPPLIER_WRITE,
  PERMISSIONS.RFQ_READ,
  PERMISSIONS.RFQ_WRITE,
  PERMISSIONS.RFQ_AWARD,
  PERMISSIONS.QUOTATION_READ,
  PERMISSIONS.PO_READ,
  PERMISSIONS.PO_WRITE,
  PERMISSIONS.PO_ISSUE,
  PERMISSIONS.CONTRACT_READ,
  PERMISSIONS.CONTRACT_WRITE,
  PERMISSIONS.CERTIFICATE_READ,
  PERMISSIONS.CERTIFICATE_WRITE,
  PERMISSIONS.DASHBOARD_READ,
  PERMISSIONS.REPORT_READ,
  PERMISSIONS.AI_USE,
];

export const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  [ROLES.SUPER_ADMIN]: [...ALL],
  [ROLES.PROCUREMENT_MANAGER]: [
    ...BUYER_PERMISSIONS,
    PERMISSIONS.SUPPLIER_APPROVE,
    PERMISSIONS.USER_WRITE,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.BUYER]: BUYER_PERMISSIONS,
  [ROLES.DEPARTMENT_MANAGER]: [
    PERMISSIONS.PR_READ,
    PERMISSIONS.PR_READ_ALL,
    PERMISSIONS.PR_REVIEW,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_READ,
  ],
  [ROLES.END_USER]: [
    PERMISSIONS.PR_READ,
    PERMISSIONS.PR_WRITE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.PROJECT_READ,
  ],
  [ROLES.SUPPLIER]: [
    PERMISSIONS.RFQ_READ,
    PERMISSIONS.QUOTATION_READ,
    PERMISSIONS.QUOTATION_WRITE,
    PERMISSIONS.PO_READ,
    PERMISSIONS.PO_ACKNOWLEDGE,
    PERMISSIONS.CATEGORY_READ,
  ],
  [ROLES.FINANCE]: [
    PERMISSIONS.PR_READ_ALL,
    PERMISSIONS.PR_REVIEW,
    PERMISSIONS.PO_READ,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_READ,
  ],
  [ROLES.QA]: [
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.CERTIFICATE_READ,
    PERMISSIONS.CERTIFICATE_WRITE,
    PERMISSIONS.PR_READ_ALL,
  ],
  [ROLES.WAREHOUSE]: [
    PERMISSIONS.PR_READ_ALL,
    PERMISSIONS.SUPPLIER_READ,
    PERMISSIONS.PO_READ,
    PERMISSIONS.CONTRACT_READ,
  ],
};
